### ISSUE TITLE
Transition animations missing

### ISSUE THREAD

**Issue by chttrjeankr** [caimconsulting/caim-consulting-website#18]
Refer [this site](https://bootstrapmade.com/demo/NewBiz/) for scrolling transitions as we view the site.
The current version of the site somehow doesn't have that. No idea why.

**Comment by chttrjeankr** [comment]
Can you take a look at code from both websites, @aditianshu? I think it's missing JS somewhere or something.

**Comment by aditianshu** [comment]
Sure, okay, l'll check it
