### ISSUE TITLE
Make mobile site more user-friendly

### ISSUE THREAD

**Issue by caimconsulting** [caimconsulting/caim-consulting-website#42]
> ![image](https://user-images.githubusercontent.com/68963325/94359017-3b17c100-00c2-11eb-996c-a6c7814c661f.png)
> Most users access using the mobile site.

So, make sure:
* Publication listings are at the center of the page.
* Other buttons like <kbd>Apply for Assistance</kbd> are not <kbd>Our Services</kbd> are not left aligned or randomly places in a mobile site.
* Redesign advisory board (for mobile) to prevent users to scroll past 15 advisors and taking up nearly half the scroll length of the webpage.

**Comment by aditianshu** [comment]
Will be working on this.
